name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-XXXXXXXXXX \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"serviceId":"srv-XXXXXXXXXX"}'
